/**
 * App Manager Module
 * Entry point for the app manager module
 * 
 * This module is responsible for loading, displaying, and managing the web components
 * generated by the App Creator. It provides a container environment where these components
 * can run safely and communicate with each other through a controlled event system.
 */

// Export components
export { LahatApp } from './components/lahat-app.js';
export { LahatCell } from './components/lahat-cell.js';
export { WidgetDrawer } from './components/widget-drawer/widget-drawer.js';
export { ErrorContainer, ErrorMessage } from './components/ui/error-container.js';

// Export utilities
export { EventBus } from './utils/event-bus.js';
export { ErrorLevel, showError, logError, createError, handleAsyncError, withErrorHandling } from './utils/error-utils.js';
export { createCustomEvent, dispatchCustomEvent, addEventListenerWithCleanup, addMultipleEventListeners, createEventProxy, debounce, throttle } from './utils/event-utils.js';
export { isSafeComponentCode, createBasicCSP, isValidMetadata } from './utils/security-utils.js';

// Export controller
export * from './app-manager.js';

// Note: IPC handlers are not exported as they are used directly by the main process and preload script
