name: CI

on:
  push:
    branches: [ main, develop, 'chore/**', 'feature/**', 'fix/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Test core functionality on macOS (only supported platform)
  test:
    runs-on: macos-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js (Electron 34.x runtime)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run integration tests
      run: npm run test:ci
      env:
        NODE_ENV: test
        CI: true
        
  # Code quality checks (run on macOS to match main platform)
  quality:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js (Electron 34.x runtime)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check code syntax
      run: |
        # Verify all JS files are syntactically valid
        find src tests -name "*.js" -exec node --check {} \;
        echo "✓ All JavaScript files are syntactically valid"
        
    - name: Run security audit
      run: |
        npm audit --audit-level=moderate || echo "⚠️ Security audit found issues"
        
    - name: Verify project structure
      run: |
        echo "Checking Electron app structure..."
        test -f main.js && echo "✓ main.js exists"
        test -f package.json && echo "✓ package.json exists" 
        test -d src && echo "✓ src directory exists"
        test -d tests && echo "✓ tests directory exists"
        echo "✓ Project structure is valid"
        
  # Build verification (ensures app can be packaged)
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js (Electron 34.x runtime)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for broken symlinks in node_modules
      run: |
        echo "Checking for broken symlinks in node_modules..."
        find node_modules -type l ! -exec test -e {} \; -print | while read -r symlink; do
          echo "Removing broken symlink: $symlink"
          rm "$symlink"
        done
        echo "✓ Broken symlinks cleaned up"
    
    - name: Verify app can be packaged
      run: npm run pack
        
    - name: Verify build artifacts exist
      run: |
        echo "Checking build artifacts..."
        test -d dist && echo "✓ dist directory created"
        ls -la dist/ || echo "No files in dist directory"
        echo "✓ Build verification completed"